import uuid
from datetime import datetime
from sqlalchemy import Column, String, Text, Float, DateTime, ForeignKey, JSON
from sqlalchemy.orm import relationship
from app.core.database import Base

class ReviewPriorityScore(Base):
    """
    Evidence review urgency assessment based on 5-factor scoring model.
    """
    __tablename__ = "review_priority_scores"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    evidence_id = Column(String(36), ForeignKey("evidence.id", ondelete="CASCADE"), unique=True, nullable=False, index=True)
    case_id = Column(String(36), ForeignKey("cases.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # 5 Urgency Dimensions (§2.3)
    temporal_urgency_score = Column(Float, nullable=False, default=0.0) # Decay / aging risk
    integrity_urgency_score = Column(Float, nullable=False, default=0.0) # Compromised or unverified hash
    volatility_score = Column(Float, nullable=False, default=0.5) # Media volatility (RAM, CCTV, CDR vs FIR)
    downstream_impact_score = Column(Float, nullable=False, default=0.0) # Reliance in hypotheses and graph edges
    corroboration_deficit_score = Column(Float, nullable=False, default=0.0) # Lack of independent corroborating sources
    
    composite_urgency_score = Column(Float, nullable=False, default=0.0, index=True)
    suggested_review_tier = Column(String(20), nullable=False, default="P2_ROUTINE", index=True) # 'P0_CRITICAL', 'P1_HIGH', 'P2_ROUTINE'
    explanation_json = Column(JSON, default=dict, nullable=False)
    calculated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Relationships
    evidence = relationship("Evidence")
    case = relationship("Case", back_populates="review_priority_scores")


class ReviewTask(Base):
    """
    Actionable investigator evidence-review task generated by the Review Deadline Engine.
    """
    __tablename__ = "review_tasks"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    case_id = Column(String(36), ForeignKey("cases.id", ondelete="CASCADE"), nullable=False, index=True)
    evidence_id = Column(String(36), ForeignKey("evidence.id", ondelete="CASCADE"), nullable=False, index=True)
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    priority = Column(String(20), default="P1", nullable=False, index=True) # 'P0', 'P1', 'P2'
    status = Column(String(30), default="pending", nullable=False, index=True) # 'pending', 'in_review', 'reverified', 'deferred', 'closed'
    assigned_to = Column(String(36), ForeignKey("users.id"), nullable=True)
    due_date = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    resolved_at = Column(DateTime, nullable=True)

    # Relationships
    case = relationship("Case", back_populates="review_tasks")
    evidence = relationship("Evidence")
    assignee = relationship("User", foreign_keys=[assigned_to])
    action_logs = relationship("ReviewActionLog", back_populates="task", cascade="all, delete-orphan")


class ReviewActionLog(Base):
    """
    Audit log of actions performed during evidentiary review.
    """
    __tablename__ = "review_action_logs"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    task_id = Column(String(36), ForeignKey("review_tasks.id", ondelete="CASCADE"), nullable=False, index=True)
    action_taken = Column(String(50), nullable=False) # 'hash_reverified', 'witness_reinterviewed', 'metadata_updated', 'cleared', 'deferred'
    notes = Column(Text, nullable=True)
    performed_by = Column(String(36), ForeignKey("users.id"), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    task = relationship("ReviewTask", back_populates="action_logs")
    performer = relationship("User", foreign_keys=[performed_by])
