"""
DEMO / SYNTHETIC DATA SEEDER — NOT REAL CASES
==============================================================================
Seeds multiple synthetic law enforcement investigative dossiers into TRACE-X
database for testing, presentations, and algorithmic evaluation.
==============================================================================
"""

import sys
import os
from datetime import datetime, timedelta, timezone

# Add backend to pythonpath
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from app.core.database import SessionLocal
from app.core.security import get_password_hash
from app.models.user import User, UserRole
from app.models.case import Case, CaseStatus, CasePriority
from app.models.evidence import Evidence, EvidenceSourceType, IntegrityStatus
from app.services.custody_service import compute_evidence_sha256, log_custody_event

SYNTHETIC_CASES = [
    {
        "case_number": "FIR-2026-DEL-8841",
        "title": "Operation Rupee Trail: Hawala & Shell Corporate Network",
        "description": "Transnational investigation into illicit cash aggregation and hawala remittances laundered through fake export invoices generated by Vikas Exports Ltd, routed via Mumbai banking hubs to Dubai entities.",
        "status": CaseStatus.UNDER_INVESTIGATION,
        "priority": CasePriority.CRITICAL,
        "days_ago": 14,
        "evidence_list": [
            ("FIR 88/2026: Hawala Remittance Intake", EvidenceSourceType.FIR, "First Information Report registered at Connaught Place PS. Suspect Vikram Malhotra transferred INR 1.45 Crores to shell companies."),
            ("Call Detail Records (Central Delhi)", EvidenceSourceType.CDR, "Tower extract reveals 42 encrypted calls between suspect and overseas brokers."),
            ("RTGS Financial Remittance Ledger", EvidenceSourceType.FINANCIAL_RECORDS, "Bank financial ledger showing 6 foreign drafts disbursed to Dubai hub.")
        ]
    },
    {
        "case_number": "FIR-2026-CYB-1092",
        "title": "Operation DarkHydra: Healthcare Ransomware & Exfiltration",
        "description": "Multi-vector cyber attack on regional hospital database servers involving DarkHydra variant ransomware, automated crypto-wallet hopping, and encrypted Telegram exfiltration command-and-control channels.",
        "status": CaseStatus.OPEN,
        "priority": CasePriority.CRITICAL,
        "days_ago": 6,
        "evidence_list": [
            ("Server Intrusion Log Extract", EvidenceSourceType.OTHER, "Snort IDS log capturing unauthorized SSH brute-force and lateral SMB propagation."),
            ("Ransomware Binary Hash & Readme", EvidenceSourceType.OTHER, "Decryption note dropping BTC ransom address with automated countdown trigger."),
            ("Crypto Wallet Hop Transaction Ledger", EvidenceSourceType.FINANCIAL_RECORDS, "Blockchain analytics tracing 14 micro-transactions to decentralized mixing service.")
        ]
    },
    {
        "case_number": "FIR-2026-CUS-4421",
        "title": "Operation Phantom Cargo: Customs Valuation & Smuggling Ring",
        "description": "Investigation into misdeclared electronics and precious metal shipments arriving through inland container depots using forged bills of lading and rotating front companies.",
        "status": CaseStatus.UNDER_INVESTIGATION,
        "priority": CasePriority.HIGH,
        "days_ago": 21,
        "evidence_list": [
            ("Customs Bill of Entry 4421/B", EvidenceSourceType.OTHER, "Forged bill of entry declaring high-value telecommunications gear as plastic toys."),
            ("Port Terminal CCTV Surveillance", EvidenceSourceType.CCTV, "CCTV recording showing container seal tampering at dry port warehouse.")
        ]
    },
    {
        "case_number": "FIR-2026-NAR-3319",
        "title": "Operation Neon Nexus: Synthetic Narcotics Distribution Network",
        "description": "Synthetic stimulant supply chain operating across interstate courier logistics hubs, coordinating drops via dead-letter drop locations and privacy-oriented messaging.",
        "status": CaseStatus.OPEN,
        "priority": CasePriority.HIGH,
        "days_ago": 9,
        "evidence_list": [
            ("Interstate Courier Consignment Slip", EvidenceSourceType.OTHER, "Waybill for parcel containing concealed pharmaceutical contraband."),
            ("Informant Intercept Audio Transcript", EvidenceSourceType.WITNESS_STATEMENT, "Witness statement confirming warehouse location in industrial corridor.")
        ]
    },
    {
        "case_number": "FIR-2026-WLD-0782",
        "title": "Operation Golden Falcon: Wildlife Trafficking & Exotic Transit",
        "description": "Interstate trafficking syndicate dealing in protected fauna and derivatives disguised as ornamental bird supplies, coordinating transfers across international border transit points.",
        "status": CaseStatus.OPEN,
        "priority": CasePriority.MEDIUM,
        "days_ago": 30,
        "evidence_list": [
            ("Border Checkpost Seizure Report", EvidenceSourceType.OTHER, "Inspection protocol documenting concealed wildlife transit vehicle."),
            ("Suspect Mobile Device Extraction", EvidenceSourceType.CDR, "Extracted messages containing exotic specimen inventory price lists.")
        ]
    },
    {
        "case_number": "FIR-2026-FIN-9204",
        "title": "Operation Silver Gateway: Circular GST & Bogus Invoicing Scheme",
        "description": "Fictitious circular trading ecosystem generating fraudulent input tax credits through 34 paper shell entities with shared director credentials and virtual IP addresses.",
        "status": CaseStatus.UNDER_INVESTIGATION,
        "priority": CasePriority.HIGH,
        "days_ago": 45,
        "evidence_list": [
            ("GST Portal Audit & Turnover Summary", EvidenceSourceType.FINANCIAL_RECORDS, "Turnover analysis showing INR 280 Cr in circular invoices without physical goods transfer."),
            ("Director KYC Identification Dossier", EvidenceSourceType.OTHER, "Shared address records linking 12 shell firms to a single residential address.")
        ]
    },
    {
        "case_number": "FIR-2025-IDT-6651",
        "title": "Operation Mirage: Coordinated Identity Theft & SIM Box Syndicate",
        "description": "Illegal SIM card activation cluster leveraging forged identity documentation to facilitate mass automated voice phishing and OTP interception gateways.",
        "status": CaseStatus.CLOSED,
        "priority": CasePriority.MEDIUM,
        "days_ago": 90,
        "evidence_list": [
            ("RAID Seizure of 128-Port SIM Box", EvidenceSourceType.OTHER, "Hardware seizure protocol and MAC address forensic report."),
            ("Forged Aadhar Identification Cards", EvidenceSourceType.OTHER, "Digital scans of fabricated identity credentials utilized for bulk SIM acquisition.")
        ]
    },
    {
        "case_number": "FIR-2025-PRC-5120",
        "title": "Operation Blue Sentinel: Municipal Procurement Bid Collusion",
        "description": "Algorithmic collusion between competing vendors bidding on smart municipal infrastructure tenders using identical digital certificate signatures and IP pools.",
        "status": CaseStatus.CLOSED,
        "priority": CasePriority.LOW,
        "days_ago": 120,
        "evidence_list": [
            ("E-Procurement Server Access Audit", EvidenceSourceType.OTHER, "IP and digital signature matching logs demonstrating shared tender bidding origin.")
        ]
    }
]

def seed_synthetic_cases():
    print("[*] Seeding Synthetic Demonstration Cases into TRACE-X Database...")
    db = SessionLocal()
    try:
        # Check or create senior investigator user
        officer = db.query(User).filter(User.email == "inspector.malhotra@delhipolice.gov.in").first()
        if not officer:
            officer = User(
                email="inspector.malhotra@delhipolice.gov.in",
                hashed_password=get_password_hash("InvestigatorPass123!"),
                full_name="Inspector Rajesh Malhotra",
                role=UserRole.SENIOR_INVESTIGATOR,
                phone_number="+91-9876543210",
                badge_number="DL-POL-8841",
                station="Special Cell / Connaught Place PS",
                is_active=True,
                has_completed_tour=True
            )
            db.add(officer)
            db.commit()
            db.refresh(officer)

        now = datetime.now(timezone.utc)
        count = 0

        for sc in SYNTHETIC_CASES:
            existing = db.query(Case).filter(Case.case_number == sc["case_number"]).first()
            if existing:
                print(f"  [-] Case {sc['case_number']} already exists, skipping.")
                continue

            c = Case(
                case_number=sc["case_number"],
                title=sc["title"],
                description=sc["description"],
                status=sc["status"],
                priority=sc["priority"],
                created_by=officer.id,
                assigned_to=officer.id,
                created_at=now - timedelta(days=sc["days_ago"]),
                updated_at=now - timedelta(hours=2)
            )
            db.add(c)
            db.commit()
            db.refresh(c)
            count += 1

            for ev_title, ev_type, ev_desc in sc.get("evidence_list", []):
                sha256_hash = compute_evidence_sha256(f"{ev_title}::{ev_desc}::{ev_type.value}")
                ev = Evidence(
                    case_id=c.id,
                    title=ev_title,
                    description=ev_desc,
                    source_type=ev_type,
                    extracted_text=ev_desc,
                    metadata_json={"synthetic_demo": True},
                    sha256_hash=sha256_hash,
                    integrity_status=IntegrityStatus.VERIFIED,
                    event_timestamp=now - timedelta(days=sc["days_ago"] - 1),
                    uploaded_by=officer.id
                )
                db.add(ev)
                db.commit()
                db.refresh(ev)

                log_custody_event(
                    db=db,
                    evidence_id=ev.id,
                    event_type="uploaded",
                    user_id=officer.id,
                    hash_at_event=sha256_hash,
                    notes=f"Synthetic demonstration evidence intake ({sha256_hash[:12]}...)"
                )

            print(f"  [+] Seeded Case: {c.title} ({c.case_number})")

        print(f"[SUCCESS] Successfully seeded {count} synthetic cases.")
    except Exception as e:
        db.rollback()
        print(f"[ERROR] Failed to seed synthetic cases: {e}")
        raise e
    finally:
        db.close()

if __name__ == "__main__":
    seed_synthetic_cases()
