import sys
import os
from datetime import datetime, timedelta, timezone

# Add backend to pythonpath
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from app.core.database import SessionLocal
from app.core.security import get_password_hash
from app.models.user import User, UserRole
from app.models.case import Case, CaseStatus, CasePriority
from app.models.evidence import Evidence, EvidenceSourceType, IntegrityStatus, CustodyEvent
from app.models.entity import Entity, EntityType, Relationship, RelationshipType
from app.models.hypothesis import Hypothesis, HypothesisStatus, EvidenceHypothesis, HypothesisRelationType
from app.models.action import InvestigativeAction, ActionType, ActionStatus
from app.models.structured import CDRRecord, FinancialTransaction
from app.services.custody_service import compute_evidence_sha256, log_custody_event
from app.services.quality_engine import recalculate_case_evidence_quality
from app.services.hypothesis_engine import recalculate_case_hypotheses
from app.services.action_engine import prioritize_case_actions
from app.core.database import Base, engine
import app.models

def seed_demo():
    print("[*] Starting TRACE-X Production Demo Case Seeder...")
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()

    try:
        # 1. Seed Demo Users with Law Enforcement Profile Metadata
        users = [
            ("admin@tracex.gov.in", "AdminPass123!", "Director General (Admin)", UserRole.ADMIN, "+91-9810011000", "MHA-DIR-001", "Ministry of Home Affairs HQ"),
            ("inspector.malhotra@delhipolice.gov.in", "InvestigatorPass123!", "Inspector Rajesh Malhotra", UserRole.SENIOR_INVESTIGATOR, "+91-9876543210", "DL-POL-8841", "Special Cell / Connaught Place PS"),
            ("officer.singh@delhipolice.gov.in", "InvestigatorPass123!", "Sub-Inspector Amit Singh", UserRole.INVESTIGATOR, "+91-9876500001", "DL-POL-9902", "Crime Branch / Central Delhi"),
            ("auditor@mha.gov.in", "AuditorPass123!", "Auditor K. Verma", UserRole.AUDITOR, "+91-9810022000", "AUD-GOV-501", "Central Evidentiary Audit Board"),
        ]
        user_map = {}
        for email, pwd, name, role, phone, badge, station in users:
            existing = db.query(User).filter(User.email == email).first()
            if not existing:
                u = User(
                    email=email,
                    hashed_password=get_password_hash(pwd),
                    full_name=name,
                    role=role,
                    phone_number=phone,
                    badge_number=badge,
                    station=station,
                    is_active=True,
                    has_completed_tour=False
                )
                db.add(u)
                db.commit()
                db.refresh(u)
                user_map[role] = u
                print(f"  [+] Created User: {email} ({role.value}) [Badge: {badge}]")
            else:
                existing.hashed_password = get_password_hash(pwd)
                existing.role = role
                existing.full_name = name
                existing.phone_number = phone
                existing.badge_number = badge
                existing.station = station
                existing.is_active = True
                db.commit()
                db.refresh(existing)
                user_map[role] = existing
                print(f"  [*] Updated User: {email} ({role.value}) [Badge: {badge}]")

        senior_inv = user_map[UserRole.SENIOR_INVESTIGATOR]

        # 2. Seed Primary Demonstration Case
        case_number = "FIR-2026-DEL-8841"
        existing_case = db.query(Case).filter(Case.case_number == case_number).first()
        if existing_case:
            print(f"  [*] Case {case_number} already exists, deleting for fresh seed...")
            db.delete(existing_case)
            db.commit()

        demo_case = Case(
            title="Operation Rupee Trail: Hawala & Shell Corporate Network",
            case_number=case_number,
            description="Transnational investigation into illicit cash aggregation and hawala remittances laundered through fake export invoices generated by Vikas Exports Ltd, routed via Mumbai banking hubs to Dubai entities.",
            status=CaseStatus.UNDER_INVESTIGATION,
            priority=CasePriority.CRITICAL,
            created_by=senior_inv.id,
            assigned_to=senior_inv.id
        )
        db.add(demo_case)
        db.commit()
        db.refresh(demo_case)
        case_id = demo_case.id
        print(f"  [+] Created Demo Case: {demo_case.title} ({case_number})")

        # 3. Seed Evidence Documents with SHA-256 Hashes and Custody Chain
        now = datetime.now(timezone.utc)
        evidence_data = [
            (
                "FIR 88/2026: Financial Fraud & Money Laundering",
                EvidenceSourceType.FIR,
                "First Information Report registered at Connaught Place PS. Suspect Vikram Malhotra (+91-9876543210) transferred INR 1.45 Crores from account 40918821 to Vikas Exports Ltd without customs clearance documentation.",
                now - timedelta(days=2),
                {"file_type": "official_fir", "police_station": "Connaught Place", "inr_amount": 14500000}
            ),
            (
                "Telco Call Detail Records (Tower B4 - Central Delhi)",
                EvidenceSourceType.CDR,
                "Tower extract reveals 42 encrypted calls between mobile +91-9876543210 (Vikram Malhotra) and suspected hawala broker +91-9811223344 prior to international fund transfers.",
                now - timedelta(days=5),
                {"format": "csv", "detected_phone_numbers": ["+919876543210", "+919811223344"], "call_count": 42}
            ),
            (
                "Bank Financial Audit & RTGS Remittance Ledger",
                EvidenceSourceType.FINANCIAL_RECORDS,
                "Financial Intelligence Unit ledger shows INR 1.45 Crores disbursed to Vikas Exports Ltd, subsequently structured into 6 foreign drafts to Dubai Remittance Hub.",
                now - timedelta(days=8),
                {"format": "json", "disbursed_inr": 14500000, "destination": "Dubai"}
            ),
            (
                "CCTV Footage Extract: Terminal 3 Departure Gates",
                EvidenceSourceType.CCTV,
                "Surveillance footage confirming suspect Vikram Malhotra entering VIP Lounge Terminal 3 at 21:40 hrs carrying briefcase containing duplicate registration certificates.",
                now - timedelta(days=12),
                {"format": "mp4", "camera_id": "DEL-T3-VIP-04", "timestamp": "21:40:00"}
            ),
            (
                "Confidential Informant Tip (Hawala Operation Hub)",
                EvidenceSourceType.ANONYMOUS_TIP,
                "Informant reports that Vikas Exports Ltd has no physical manufacturing warehouse and operations are managed out of a residential property in Lajpat Nagar.",
                now - timedelta(days=18),
                {"reliability": "unverified", "informant_id": "SOURCE-DEL-09"}
            )
        ]

        evidence_objects = []
        for title, stype, text, ev_time, meta in evidence_data:
            # Cryptographic SHA-256 computation
            sha256_hash = compute_evidence_sha256(f"{title}::{text}::{stype.value}")

            ev = Evidence(
                case_id=case_id,
                title=title,
                description="Seeded evidentiary document with immutable cryptographic provenance.",
                source_type=stype,
                extracted_text=text,
                metadata_json=meta,
                sha256_hash=sha256_hash,
                integrity_status=IntegrityStatus.VERIFIED,
                event_timestamp=ev_time,
                uploaded_by=senior_inv.id
            )
            db.add(ev)
            db.commit()
            db.refresh(ev)
            evidence_objects.append(ev)

            # Record Ingestion Custody Event
            log_custody_event(
                db=db,
                evidence_id=ev.id,
                event_type="uploaded",
                user_id=senior_inv.id,
                hash_at_event=sha256_hash,
                notes=f"Evidentiary intake registered under SHA-256 standard ({sha256_hash[:12]}...)"
            )

        print(f"  [+] Ingested {len(evidence_objects)} evidence items with SHA-256 digests and custody chains.")

        # Seed Structured CDR Rows for CDR Evidence
        cdr_ev = next((e for e in evidence_objects if e.source_type == EvidenceSourceType.CDR), None)
        if cdr_ev:
            cdr_samples = [
                ("+91-9876543210", "+91-9811223344", 180, "Tower B4 - Central Delhi"),
                ("+91-9876543210", "+91-9811223344", 240, "Tower B4 - Central Delhi"),
                ("+91-9876543210", "+91-9811223344", 95, "Tower B4 - Central Delhi"),
                ("+91-9876543210", "+91-9811223344", 310, "Tower B4 - Central Delhi"),
                ("+91-9811223344", "+971-501234567", 450, "Tower B4 - Central Delhi"),
            ]
            for c_from, c_to, dur, twr in cdr_samples:
                db.add(CDRRecord(
                    evidence_id=cdr_ev.id,
                    caller_number=c_from,
                    receiver_number=c_to,
                    call_timestamp=datetime.utcnow() - timedelta(days=5),
                    duration_seconds=dur,
                    tower_location=twr
                ))
            db.commit()

        # Seed Structured Financial Transactions for Bank Evidence
        fin_ev = next((e for e in evidence_objects if e.source_type == EvidenceSourceType.FINANCIAL_RECORDS), None)
        if fin_ev:
            fin_samples = [
                ("Vikram Malhotra", "Vikas Exports Ltd", 14500000.0, "State Bank of India"),
                ("Vikas Exports Ltd", "Dubai Remittance Hub", 14500000.0, "Emirates NBD"),
                ("Vikram Malhotra", "Lajpat Nagar Safehouse", 2500000.0, "HDFC Bank")
            ]
            for s, r, amt, bnk in fin_samples:
                db.add(FinancialTransaction(
                    evidence_id=fin_ev.id,
                    sender=s,
                    receiver=r,
                    amount=amt,
                    txn_timestamp=datetime.utcnow() - timedelta(days=8),
                    bank_name=bnk
                ))
            db.commit()

        # 4. Seed Entities & Graph Relationships
        entities_data = [
            ("Vikram Malhotra", EntityType.PERSON, 0.98, {"role": "Primary Suspect", "pan": "ABCDE1234F"}),
            ("Vikas Exports Ltd", EntityType.ORGANIZATION, 0.95, {"cin": "U74999DL2021PTC123456", "status": "Shell Entity"}),
            ("+91-9876543210", EntityType.PHONE, 0.99, {"operator": "Airtel Delhi", "imei": "864209048123456"}),
            ("+91-9811223344", EntityType.PHONE, 0.92, {"operator": "Vodafone", "registered_name": "Unknown Ali"}),
            ("Dubai Remittance Hub", EntityType.ORGANIZATION, 0.90, {"jurisdiction": "UAE", "license": "DXB-FIN-8821"}),
            ("Connaught Place PS", EntityType.LOCATION, 0.95, {"district": "New Delhi"}),
            ("DL-10-AB-9841", EntityType.VEHICLE, 0.88, {"make": "Toyota Fortuner", "color": "White"}),
            ("Lajpat Nagar Safehouse", EntityType.LOCATION, 0.78, {"address": "Block C, Lajpat Nagar IV, New Delhi"}),
        ]

        entity_objects = {}
        for name, etype, conf, attrs in entities_data:
            ent = Entity(
                case_id=case_id,
                name=name,
                entity_type=etype,
                canonical_name=name,
                confidence_score=conf,
                attributes_json=attrs
            )
            db.add(ent)
            db.commit()
            db.refresh(ent)
            entity_objects[name] = ent

        # Seed Relationships
        relationships_data = [
            ("Vikram Malhotra", "Vikas Exports Ltd", RelationshipType.CONNECTED_TO, 0.95),
            ("Vikram Malhotra", "+91-9876543210", RelationshipType.OWNS, 0.99),
            ("+91-9876543210", "+91-9811223344", RelationshipType.CALLS, 0.92),
            ("Vikas Exports Ltd", "Dubai Remittance Hub", RelationshipType.TRANSFERRED_TO, 0.90),
            ("Vikram Malhotra", "DL-10-AB-9841", RelationshipType.OWNS, 0.88),
            ("Vikram Malhotra", "Lajpat Nagar Safehouse", RelationshipType.LOCATED_AT, 0.75),
        ]

        for src_name, tgt_name, rel_type, weight in relationships_data:
            src = entity_objects.get(src_name)
            tgt = entity_objects.get(tgt_name)
            if src and tgt:
                rel = Relationship(
                    case_id=case_id,
                    source_entity_id=src.id,
                    target_entity_id=tgt.id,
                    relationship_type=rel_type,
                    weight=weight,
                    confidence_score=weight
                )
                db.add(rel)
        db.commit()
        print(f"  [+] Seeded {len(entity_objects)} Entities and {len(relationships_data)} Graph Relationships.")

        # 5. Compute 4D Evidence Quality Scores
        recalc_res = recalculate_case_evidence_quality(db, case_id)
        print(f"  [+] Calculated 4D Evidence Quality Scores: {recalc_res.get('evidence_items_recalculated', 0)} items.")

        # 6. Seed Richards Heuer ACH Competing Hypotheses
        hypotheses_data = [
            (
                "Hypothesis A: Organized Hawala & Shell Company Network",
                "Vikram Malhotra systematically orchestrated shell trade invoices via Vikas Exports Ltd to transmit illicit cash to offshore Dubai accounts.",
                senior_inv.id
            ),
            (
                "Hypothesis B: Legitimate Textile Export Business",
                "Vikas Exports Ltd engaged in lawful textile exports with delayed customs documentation due to logistics disruption.",
                senior_inv.id
            ),
            (
                "Hypothesis C: Third-Party Identity Theft / Proxy Operation",
                "Vikram Malhotra's corporate credentials and phone number were impersonated by an unknown criminal syndicate without his direct consent.",
                senior_inv.id
            )
        ]

        hyp_objects = []
        for h_title, h_desc, created_by in hypotheses_data:
            hyp = Hypothesis(
                case_id=case_id,
                title=h_title,
                description=h_desc,
                status=HypothesisStatus.ACTIVE,
                created_by=created_by
            )
            db.add(hyp)
            db.commit()
            db.refresh(hyp)
            hyp_objects.append(hyp)

        # Link Evidence to Hypotheses with Diagnostic Contradiction Weights
        ev_map = {e.source_type: e for e in evidence_objects}
        fir_ev = ev_map[EvidenceSourceType.FIR]
        cdr_ev = ev_map[EvidenceSourceType.CDR]
        fin_ev = ev_map[EvidenceSourceType.FINANCIAL_RECORDS]
        cctv_ev = ev_map[EvidenceSourceType.CCTV]

        links = [
            # Hyp A (Organized Hawala)
            (hyp_objects[0].id, fir_ev.id, HypothesisRelationType.SUPPORTS, 0.90, "FIR documents fraudulent unverified invoice."),
            (hyp_objects[0].id, cdr_ev.id, HypothesisRelationType.SUPPORTS, 0.85, "High frequency communication with suspected broker."),
            (hyp_objects[0].id, fin_ev.id, HypothesisRelationType.SUPPORTS, 0.95, "Layered foreign drafts to Dubai match Hawala pattern."),
            # Hyp B (Legitimate Export)
            (hyp_objects[1].id, fin_ev.id, HypothesisRelationType.CONTRADICTS, 0.95, "No corresponding bill of lading found for 1.45 Cr remittance."),
            (hyp_objects[1].id, cdr_ev.id, HypothesisRelationType.CONTRADICTS, 0.80, "Encrypted call volume is inconsistent with standard commercial trade."),
            # Hyp C (Identity Theft)
            (hyp_objects[2].id, cctv_ev.id, HypothesisRelationType.CONTRADICTS, 0.90, "CCTV confirms suspect physically present handling duplicate registrations."),
        ]

        for h_id, e_id, r_type, strength, rationale in links:
            eh = EvidenceHypothesis(
                hypothesis_id=h_id,
                evidence_id=e_id,
                relationship_type=r_type,
                relationship_strength=strength,
                rationale=rationale,
                linked_by=senior_inv.id
            )
            db.add(eh)
        db.commit()

        # Recalculate ACH Scores with 1.5x Contradiction Penalty
        ach_res = recalculate_case_hypotheses(db, case_id)
        print(f"  [+] Evaluated Heuer ACH Matrix with 1.5x Diagnostic Multiplier.")

        # 7. Seed Value-of-Information (VoI) Ranked Actions
        actions_data = [
            (
                "Subpoena Dubai Remittance Hub Beneficial Ownership via MLAT",
                "Execute mutual legal assistance treaty (MLAT) request to UAE authorities to uncover ultimate beneficial owner of Dubai Remittance Hub.",
                ActionType.OBTAIN_FINANCIAL_RECORDS,
                entity_objects["Dubai Remittance Hub"].id,
                senior_inv.id
            ),
            (
                "Forensic Handset & IMEI Triage on Vikram Malhotra",
                "Extract WhatsApp encrypted chat backups and crypto-wallet addresses from seized handset (+91-9876543210).",
                ActionType.FORENSIC_ANALYSIS,
                entity_objects["Vikram Malhotra"].id,
                senior_inv.id
            ),
            (
                "CCTV Surveillance Audit on Lajpat Nagar Safehouse",
                "Retrieve 14-day DVR footage from neighbor retail shops facing the alleged Lajpat Nagar aggregation premises.",
                ActionType.CCTV_REVIEW,
                entity_objects["Lajpat Nagar Safehouse"].id,
                senior_inv.id
            )
        ]

        for a_title, a_desc, a_type, ent_id, assigned_to in actions_data:
            act = InvestigativeAction(
                case_id=case_id,
                title=a_title,
                description=a_desc,
                action_type=a_type,
                status=ActionStatus.PENDING,
                target_entity_id=ent_id,
                assigned_to=assigned_to,
                base_gain=0.85
            )
            db.add(act)
        db.commit()

        # 8. Seed Enhanced Officer Profiles & Case Memberships
        from app.models.officer_extension import OfficerProfile, OfficerStatusHistory, OfficerRoleHistory, CaseMembership
        for role, u in user_map.items():
            existing_prof = db.query(OfficerProfile).filter(OfficerProfile.user_id == u.id).first()
            if not existing_prof:
                prof = OfficerProfile(
                    user_id=u.id,
                    designation="Senior Investigating Officer" if u.role == UserRole.SENIOR_INVESTIGATOR else "Commanding Officer",
                    district="New Delhi & Central",
                    state="Delhi (NCT)",
                    rank="Inspector" if u.role == UserRole.SENIOR_INVESTIGATOR else "Director",
                    department="Special Cyber & Financial Crime Cell"
                )
                db.add(prof)

                # Add Case Membership
                mem = CaseMembership(
                    case_id=case_id,
                    user_id=u.id,
                    assignment_role="lead" if u.role == UserRole.SENIOR_INVESTIGATOR else "investigator",
                    is_active=True,
                    assigned_by=user_map[UserRole.ADMIN].id,
                    assigned_at=datetime.utcnow()
                )
                db.add(mem)
        db.commit()
        print("  [+] Configured Enhanced Officer Profiles & Case Memberships.")

        # 9. Seed Default Content CMS Pages
        from app.models.content_cms import ContentPage, ContentPageVersion, ContentPageStatus
        existing_about = db.query(ContentPage).filter(ContentPage.slug == "about-us").first()
        if not existing_about:
            about_page = ContentPage(
                slug="about-us",
                title="About TRACE-X Intelligence Platform",
                summary="Transformative Relational Analytics & Criminal Evidence Cross-Examination for national security and economic intelligence.",
                body_markdown="""# TRACE-X: Advanced Law Enforcement Relational Intelligence

## Institutional Overview
**TRACE-X** (Transformative Relational Analytics & Criminal Evidence Cross-Examination) is an enterprise-grade investigative intelligence platform designed for police departments, economic intelligence units, and federal crime agencies.

### Core Mathematical & AI Innovations
1. **4D Evidence Quality Scoring**: Multi-variable weighting ($Q(e) = 0.35S + 0.20T + 0.30C + 0.15D$) with continuous exponential decay tracking.
2. **Analysis of Competing Hypotheses (ACH)**: Richards Heuer diagnostic contradiction matrix with calibrated likelihood estimators.
3. **Value-of-Information Action Prioritizer**: Decision-theoretic engine calculating Expected Information Gain (EIG) to optimize investigative resource allocation.
4. **Cryptographic Chain of Custody**: Continuous SHA-256 evidence hashing and immutable audit logging.
5. **Counterfactual Simulation & Resilience Testing**: High-fidelity scenario exploration without baseline distortion.

---

### Built for Inter-Agency Standards
TRACE-X conforms strictly to legal chain-of-custody protocols, judicial admissibility guidelines, and multi-tier role-based access control.""",
                status=ContentPageStatus.PUBLISHED,
                current_version=1,
                author_id=user_map[UserRole.ADMIN].id,
                published_at=datetime.utcnow()
            )
            db.add(about_page)
            db.commit()
            db.refresh(about_page)

            v1 = ContentPageVersion(
                page_id=about_page.id,
                version_number=1,
                title=about_page.title,
                summary=about_page.summary,
                body_markdown=about_page.body_markdown,
                status=about_page.status,
                created_by=user_map[UserRole.ADMIN].id,
                change_summary="Initial system release"
            )
            db.add(v1)
            db.commit()
            print("  [+] Seeded Published Content CMS Page (about-us).")

        # 10. Seed Interactive Tutorials
        from app.models.tutorial import Tutorial
        tut_count = db.query(Tutorial).count()
        if tut_count == 0:
            tut1 = Tutorial(
                title="Mastering Heuer Competing Hypotheses (ACH)",
                description="Learn how the 1.5x contradiction diagnostic penalty operates in TRACE-X to eliminate cognitive bias.",
                category="ACH Hypotheses",
                video_url="https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                youtube_id="dQw4w9WgXcQ",
                duration_minutes=8,
                order_index=1,
                is_published=True,
                steps_json=[
                    {
                        "step_number": 1,
                        "title": "Open Competing Hypotheses View",
                        "detail": "Navigate to the case ACH workspace to view all mutually exclusive scenarios.",
                        "hint": "Check the likelihood gauge on each card."
                    },
                    {
                        "step_number": 2,
                        "title": "Evaluate 1.5x Contradiction Weight",
                        "detail": "Link evidence items as consistent, neutral, or inconsistent. Note how contradictions penalize likelihood faster than corroboration boosts it.",
                        "hint": "Richards Heuer's core principle states disproving alternatives is more diagnostic."
                    },
                    {
                        "step_number": 3,
                        "title": "Run Side-by-Side Comparison",
                        "detail": "Select two hypotheses to run comparative diagnostic evidence differential analysis.",
                        "hint": "Highlight diagnostic evidence distinguishing both theories."
                    }
                ]
            )
            tut2 = Tutorial(
                title="4D Evidence Quality Graph & Exponential Decay",
                description="Understand how source reliability, temporal freshness, cross-corroboration, and chain-of-custody combine into a single quality score.",
                category="Graph Analysis",
                video_url="https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                youtube_id="dQw4w9WgXcQ",
                duration_minutes=6,
                order_index=2,
                is_published=True,
                steps_json=[
                    {
                        "step_number": 1,
                        "title": "Inspect Multi-Ring Evidence Nodes",
                        "detail": "View Green (≥70%), Amber (40-70%), and Red (<40%) quality rings on the interactive React Flow canvas.",
                        "hint": "Ring thickness denotes degree of cross-corroboration."
                    },
                    {
                        "step_number": 2,
                        "title": "Review 30-Day Temporal Decay",
                        "detail": "Check how time-sensitive evidence degrades over time unless re-verified by field investigators.",
                        "hint": "Decay follows lambda = 0.0231 (30-day half-life)."
                    }
                ]
            )
            tut3 = Tutorial(
                title="Value-of-Information (VoI) Expected Information Gain",
                description="Maximize investigative efficiency by executing actions that yield the highest expected entropy reduction.",
                category="VoI Prioritization",
                video_url="https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                youtube_id="dQw4w9WgXcQ",
                duration_minutes=5,
                order_index=3,
                is_published=True,
                steps_json=[
                    {
                        "step_number": 1,
                        "title": "Inspect Action Gain Breakdown",
                        "detail": "Review the Expected Information Gain formula multiplier components.",
                        "hint": "EIG = Base * gap_multiplier * hyp_uncertainty * feasibility."
                    },
                    {
                        "step_number": 2,
                        "title": "Log Investigative Outcome",
                        "detail": "Mark action completed and log findings to automatically update hypothesis likelihoods.",
                        "hint": "Completing actions triggers instant graph recalculation."
                    }
                ]
            )
            db.add_all([tut1, tut2, tut3])
            db.commit()
            print("  [+] Seeded 3 Interactive Training Tutorials.")

        # 11. Seed Themes & Feature Flags
        from app.models.theme import ThemeConfiguration, ThemeVersion
        from app.models.feature_flag import FeatureFlag
        from app.api.v1.endpoints.feature_flags import ensure_default_flags

        ensure_default_flags(db)
        print("  [+] Initialized 5 Production Feature Flags.")

        theme_count = db.query(ThemeConfiguration).count()
        if theme_count == 0:
            theme1 = ThemeConfiguration(
                name="Default Cyber Cyan",
                primary_color="#06b6d4",
                accent_color="#3b82f6",
                background_mode="slate",
                font_family="Inter",
                border_radius="0.75rem",
                is_active=True,
                custom_css_vars={"--color-brand-primary": "#06b6d4", "--color-brand-accent": "#3b82f6"}
            )
            db.add(theme1)
            db.commit()
            db.refresh(theme1)
            t_v = ThemeVersion(
                theme_id=theme1.id,
                version_number=1,
                config_json={"name": theme1.name, "primary_color": theme1.primary_color},
                change_notes="Initial base palette release",
                created_by=user_map[UserRole.ADMIN].id
            )
            db.add(t_v)
            db.commit()
            print("  [+] Seeded Active System Theme Configuration.")

        print(f"\n[SUCCESS] TRACE-X Production Demonstration Case ({case_number}) Seeded Successfully!")
        print("="*75)
        print("DEMO CREDENTIALS:")
        print("  • Senior Investigator : inspector.malhotra@delhipolice.gov.in / InvestigatorPass123!")
        print("  • Chief Administrator : admin@tracex.gov.in / AdminPass123!")
        print("  • Field Investigator  : officer.singh@delhipolice.gov.in / InvestigatorPass123!")
        print("  • Independent Auditor : auditor@mha.gov.in / AuditorPass123!")
        print("="*75)

    except Exception as e:
        db.rollback()
        print(f"[ERROR] Seeder failed: {e}")
        raise
    finally:
        db.close()

if __name__ == "__main__":
    seed_demo()
