/**
 * DEMO / SYNTHETIC DATA — NOT REAL CASES
 * ==============================================================================
 * This file contains strictly synthetic, fictional case records generated for
 * law enforcement technical evaluation, testing, and UI demonstration purposes.
 * No real persons, active intelligence operations, or sensitive agency data are used.
 * ==============================================================================
 */

import { Case } from '../types';

export const DEMO_CASES: Case[] = [
  {
    id: 'demo-case-001',
    case_number: 'FIR-2026-DEL-8841',
    title: 'Operation Rupee Trail: Hawala & Shell Corporate Network',
    description: 'Transnational investigation into illicit cash aggregation and hawala remittances laundered through fake export invoices generated by Vikas Exports Ltd, routed via Mumbai banking hubs to Dubai entities.',
    status: 'under_investigation',
    priority: 'critical',
    created_by: 'demo-officer-01',
    assigned_to: 'demo-officer-01',
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    evidence_count: 5,
    entity_count: 12,
    hypothesis_count: 3,
    action_count: 4,
    creator: {
      id: 'demo-officer-01',
      email: 'inspector.malhotra@delhipolice.gov.in',
      full_name: 'Inspector Rajesh Malhotra',
      role: 'senior_investigator',
      badge_number: 'DL-POL-8841',
      station: 'Special Cell / Connaught Place PS',
      is_active: true,
      has_completed_tour: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString()
    }
  },
  {
    id: 'demo-case-002',
    case_number: 'FIR-2026-CYB-1092',
    title: 'Operation DarkHydra: Healthcare Ransomware & Exfiltration',
    description: 'Multi-vector cyber attack on regional hospital database servers involving DarkHydra variant ransomware, automated crypto-wallet hopping, and encrypted Telegram exfiltration command-and-control channels.',
    status: 'open',
    priority: 'critical',
    created_by: 'demo-officer-02',
    assigned_to: 'demo-officer-02',
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    evidence_count: 8,
    entity_count: 19,
    hypothesis_count: 4,
    action_count: 6,
    creator: {
      id: 'demo-officer-02',
      email: 'officer.singh@delhipolice.gov.in',
      full_name: 'Sub-Inspector Amit Singh',
      role: 'investigator',
      badge_number: 'DL-POL-9902',
      station: 'Cyber Crime Division / Central Delhi',
      is_active: true,
      has_completed_tour: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString()
    }
  },
  {
    id: 'demo-case-003',
    case_number: 'FIR-2026-CUS-4421',
    title: 'Operation Phantom Cargo: Customs Valuation & Smuggling Ring',
    description: 'Investigation into misdeclared electronics and precious metal shipments arriving through inland container depots using forged bills of lading and rotating front companies.',
    status: 'under_investigation',
    priority: 'high',
    created_by: 'demo-officer-01',
    assigned_to: 'demo-officer-01',
    created_at: new Date(Date.now() - 21 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    evidence_count: 6,
    entity_count: 14,
    hypothesis_count: 2,
    action_count: 3
  },
  {
    id: 'demo-case-004',
    case_number: 'FIR-2026-NAR-3319',
    title: 'Operation Neon Nexus: Synthetic Narcotics Distribution Network',
    description: 'Synthetic stimulant supply chain operating across interstate courier logistics hubs, coordinating drops via dead-letter drop locations and privacy-oriented messaging.',
    status: 'open',
    priority: 'high',
    created_by: 'demo-officer-02',
    assigned_to: 'demo-officer-01',
    created_at: new Date(Date.now() - 9 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 12 * 3600000).toISOString(),
    evidence_count: 7,
    entity_count: 16,
    hypothesis_count: 3,
    action_count: 5
  },
  {
    id: 'demo-case-005',
    case_number: 'FIR-2026-WLD-0782',
    title: 'Operation Golden Falcon: Wildlife Trafficking & Exotic Transit',
    description: 'Interstate trafficking syndicate dealing in protected fauna and derivatives disguised as ornamental bird supplies, coordinating transfers across international border transit points.',
    status: 'open',
    priority: 'medium',
    created_by: 'demo-officer-01',
    assigned_to: 'demo-officer-02',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    evidence_count: 4,
    entity_count: 9,
    hypothesis_count: 2,
    action_count: 2
  },
  {
    id: 'demo-case-006',
    case_number: 'FIR-2026-FIN-9204',
    title: 'Operation Silver Gateway: Circular GST & Bogus Invoicing Scheme',
    description: 'Fictitious circular trading ecosystem generating fraudulent input tax credits through 34 paper shell entities with shared director credentials and virtual IP addresses.',
    status: 'under_investigation',
    priority: 'high',
    created_by: 'demo-officer-01',
    assigned_to: 'demo-officer-01',
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 3600000).toISOString(),
    evidence_count: 11,
    entity_count: 26,
    hypothesis_count: 5,
    action_count: 7
  },
  {
    id: 'demo-case-007',
    case_number: 'FIR-2025-IDT-6651',
    title: 'Operation Mirage: Coordinated Identity Theft & SIM Box Syndicate',
    description: 'Illegal SIM card activation cluster leveraging forged identity documentation to facilitate mass automated voice phishing and OTP interception gateways.',
    status: 'closed',
    priority: 'medium',
    created_by: 'demo-officer-02',
    assigned_to: 'demo-officer-02',
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    evidence_count: 9,
    entity_count: 18,
    hypothesis_count: 3,
    action_count: 4
  },
  {
    id: 'demo-case-008',
    case_number: 'FIR-2025-PRC-5120',
    title: 'Operation Blue Sentinel: Municipal Procurement Bid Collusion',
    description: 'Algorithmic collusion between competing vendors bidding on smart municipal infrastructure tenders using identical digital certificate signatures and IP pools.',
    status: 'closed',
    priority: 'low',
    created_by: 'demo-officer-01',
    assigned_to: 'demo-officer-01',
    created_at: new Date(Date.now() - 120 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 40 * 86400000).toISOString(),
    evidence_count: 5,
    entity_count: 11,
    hypothesis_count: 2,
    action_count: 3
  }
];
